/**
 * Outbound email signature
 * ------------------------
 *
 * Two modes are supported, controlled by `settings.email_signature_format`:
 *
 *   - `plain` (default) — the signature is plain text from
 *     `settings.email_signature`. The HTML form is generated by escaping
 *     + wrapping in `<div style="white-space:pre-wrap">…</div>` so
 *     newlines survive.
 *   - `html`  — the signature is rich HTML from
 *     `settings.email_signature_html`. The signature is run through an
 *     allowlist sanitizer (`sanitizeRichSignature`) that strips
 *     anything dangerous. The plain-text form is derived from the
 *     sanitized HTML (`htmlToText`).
 *
 * Either way the returned object is:
 *   { raw, text, html }
 *
 * where `raw` is the canonical "is this already appended?" value
 * (the trimmed configured signature content), `text` is what goes
 * into the email's `text:` field, and `html` is what goes into the
 * email's `html:` field (or null when no signature is configured).
 *
 * SECURITY MODEL
 * --------------
 * 1. Plain mode is unchanged from the original: signatures are
 *    HTML-escaped, no HTML is ever trusted from a signature field.
 * 2. HTML mode opts in via a separate `email_signature_format` setting
 *    and a separate `email_signature_html` field. Admins who want rich
 *    signatures can opt in. The default is still `plain`, so existing
 *    deployments see zero behavior change.
 * 3. The HTML signature goes through an allowlist sanitizer
 *    (`sanitizeRichSignature`) before being embedded in outgoing
 *    email. The sanitizer is intentionally strict:
 *    - Tag allowlist: a, b, strong, i, em, u, span, div, p, br, img,
 *      table/tr/td/th, h1-h6, ul, ol, li, blockquote, hr, small,
 *      sub, sup, font.
 *    - Attribute allowlist: href (http/https/mailto), src
 *      (http/https), alt, title, style, target, rel, colspan, rowspan.
 *    - Strips: <script>, <style>, <iframe>, <object>, <embed>,
 *      <form>, <link>, <meta>, <base>, all on* event handlers, all
 *      `javascript:` / `data:` / `vbscript:` URLs.
 * 4. Plain-text is derived from the sanitized HTML, not the original
 *    admin input — so an admin who accidentally pastes something
 *    dangerous sees it reflected as plain text (not executed), and a
 *    block-tag conversion (<p>→\n\n, <br>→\n) keeps the layout
 *    roughly intact in the text body.
 * 5. The customer's reply text remains escaped as before
 *    (`<div style="white-space:pre-wrap">${escapeHtml(trimmed)}</div>`)
 *    — only the signature is allowed to be rich.
 *
 * If no signature is configured, returns `null` so callers can skip
 * the append step entirely.
 */

import { escapeHtml } from './text.js';

// ---------------------------------------------------------------------------
// Sanitizer (allowlist) for admin-authored HTML signatures.
// ---------------------------------------------------------------------------

// Tag allowlist. Anything not in this list (after the attr scrub) is
// dropped, with its inner text preserved.
const ALLOWED_TAGS = new Set([
  'a', 'b', 'strong', 'i', 'em', 'u', 'span', 'div', 'p', 'br',
  'img', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ul', 'ol', 'li',
  'blockquote', 'hr', 'small', 'sub', 'sup', 'font', 'table',
  'thead', 'tbody', 'tfoot', 'tr', 'th', 'td',
]);

// Attributes allowed on each tag. Conservative: style is OK (admin
// wants to set fonts/colors), target is OK (so links can open new
// tabs), and table cell merging is allowed. `title` is allowed on
// nearly all visible tags for tooltip text; `alt` is allowed on img.
// Most inline text tags also get `title` to keep the surface useful.
const COMMON_TITLE = new Set(['title']);
const ALLOWED_ATTRS = {
  a: new Set(['href', 'title', 'target', 'rel', 'style']),
  img: new Set(['src', 'alt', 'title', 'width', 'height', 'style']),
  span: new Set(['style', 'title']),
  div: new Set(['style', 'title']),
  p: new Set(['style', 'title']),
  font: new Set(['color', 'face', 'size', 'title']),
  table: new Set(['style', 'title', 'width', 'cellpadding', 'cellspacing', 'border']),
  th: new Set(['colspan', 'rowspan', 'style', 'width', 'title']),
  td: new Set(['colspan', 'rowspan', 'style', 'width', 'title']),
  tr: new Set(['style', 'title']),
  thead: new Set(['title']),
  tbody: new Set(['title']),
  tfoot: new Set(['title']),
  ul: new Set(['style', 'title']),
  ol: new Set(['style', 'title', 'start']),
  li: new Set(['style', 'title']),
  h1: new Set(['style', 'title']),
  h2: new Set(['style', 'title']),
  h3: new Set(['style', 'title']),
  h4: new Set(['style', 'title']),
  h5: new Set(['style', 'title']),
  h6: new Set(['style', 'title']),
  blockquote: new Set(['style', 'title']),
  hr: new Set([]),
  small: new Set(['title']),
  sub: new Set(['title']),
  sup: new Set(['title']),
  b: new Set(['title']),
  strong: new Set(['title']),
  i: new Set(['title']),
  em: new Set(['title']),
  u: new Set(['title']),
  br: new Set([]),
};
// Silence "unused" lint for COMMON_TITLE (we use it implicitly via the
// explicit allowlist above; if we ever want a global default, plug it
// in here).
void COMMON_TITLE;

// URL protocols we permit in href/src. Anything else becomes `#`.
const SAFE_PROTOCOLS = new Set(['http:', 'https:', 'mailto:']);

/**
 * Walk a tag's attributes and keep only the safe ones with safe values.
 * Returns the cleaned attribute string (without surrounding whitespace).
 */
function cleanAttrs(tagName, rawAttrs) {
  const allowed = ALLOWED_ATTRS[tagName];
  if (!allowed) return '';
  // Match name="value" / name='value' / name=value (bare)
  const re = /([a-zA-Z][a-zA-Z0-9-]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g;
  const out = [];
  let m;
  while ((m = re.exec(rawAttrs)) !== null) {
    const name = m[1].toLowerCase();
    if (!allowed.has(name)) continue;
    const value = m[2] ?? m[3] ?? m[4] ?? '';
    if (name === 'href' || name === 'src') {
      // Reject javascript:, data:, vbscript:, file:, and any other
      // non-allowlisted scheme. Bare relative URLs are allowed.
      const trimmed = String(value).trim();
      if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(trimmed)) {
        const protoMatch = trimmed.match(/^([a-zA-Z][a-zA-Z0-9+.-]*:)/);
        if (protoMatch && !SAFE_PROTOCOLS.has(protoMatch[1].toLowerCase())) {
          continue; // drop the attribute entirely
        }
      }
    }
    if (name === 'style') {
      // Strip `expression(...)`, `behavior:`, and `javascript:` even
      // inside style values — defense in depth.
      const styleClean = String(value)
        .replace(/expression\s*\([^)]*\)/gi, '')
        .replace(/behavior\s*:\s*url\s*\([^)]*\)/gi, '')
        .replace(/javascript\s*:/gi, '');
      if (!styleClean.trim()) continue;
      out.push(`${name}="${escapeHtml(styleClean)}"`);
    } else {
      out.push(`${name}="${escapeHtml(value)}"`);
    }
  }
  // For <a target="_blank">, force rel="noopener noreferrer" if not set.
  if (tagName === 'a' && out.some((a) => a.startsWith('target="_blank"'))) {
    if (!out.some((a) => a.startsWith('rel='))) {
      out.push('rel="noopener noreferrer"');
    }
  }
  return out.join(' ');
}

// Block-level "void" tags (script, style, iframe, object, embed, form,
// link, meta, base): we don't render them, and we also DROP their body
// content. For all other disallowed tags, we drop the tag but emit
// the text content (so an admin's <custom>hello</custom> still has
// "hello" in the output).
const VOID_DISALLOWED = new Set(['script', 'style', 'iframe', 'object', 'embed', 'form', 'link', 'meta', 'base']);

/**
 * Sanitize admin-authored HTML for use as the rich signature. The
 * returned string is safe to embed inside an outgoing email body.
 *
 * Approach: a small stateful parser. Not a real HTML parser, but
 * sufficient for the admin's signature use case (a few lines of
 * formatted contact info, maybe a logo img and a link). Anything we
 * don't recognize gets stripped or its text content preserved.
 *
 * For tags that are disallowed because they execute (script, style,
 * iframe, object, embed, form, link, meta, base), the body content
 * is also dropped — we don't trust a `<style>body{display:none}</style>`
 * or a `<script>fetch('evil')</script>` to be safe text. For
 * unknown structural tags (e.g. <custom>), the text content is
 * preserved so simple markup mistakes don't lose data.
 */
export function sanitizeRichSignature(html) {
  if (!html || typeof html !== 'string') return '';
  // Strip <!-- comments -->
  const noComments = html.replace(/<!--[\s\S]*?-->/g, '');
  // Normalize line endings
  const src = noComments.replace(/\r\n?/g, '\n');

  let out = '';
  let i = 0;

  while (i < src.length) {
    const lt = src.indexOf('<', i);
    if (lt === -1) {
      out += escapeHtml(src.slice(i));
      break;
    }
    // Emit text before the tag
    out += escapeHtml(src.slice(i, lt));

    // Closing tag?
    const closeMatch = src.slice(lt).match(/^<\/([a-zA-Z][a-zA-Z0-9]*)\s*>/);
    if (closeMatch) {
      const tag = closeMatch[1].toLowerCase();
      if (ALLOWED_TAGS.has(tag)) {
        out += `</${tag}>`;
      } else if (VOID_DISALLOWED.has(tag)) {
        // Closing of a void-disallowed tag we never opened: nothing to
        // emit, and we DON'T need to skip ahead (we already advanced
        // past the corresponding opening tag in the loop below).
      }
      // Unknown / non-void closing tag: drop it (text content was already emitted).
      i = lt + closeMatch[0].length;
      continue;
    }

    // Opening tag (with or without self-closing /)?
    const openMatch = src.slice(lt).match(/^<([a-zA-Z][a-zA-Z0-9]*)((?:\s+[a-zA-Z][a-zA-Z0-9-]*\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))*)\s*(\/?)>/);
    if (openMatch) {
      const tag = openMatch[1].toLowerCase();
      const attrs = openMatch[2] || '';
      const selfClose = openMatch[3] === '/';
      if (ALLOWED_TAGS.has(tag)) {
        const cleaned = cleanAttrs(tag, attrs);
        if (tag === 'br' || tag === 'hr' || selfClose) {
          out += `<${tag}${cleaned ? ' ' + cleaned : ''} />`;
        } else {
          out += `<${tag}${cleaned ? ' ' + cleaned : ''}>`;
        }
        i = lt + openMatch[0].length;
        continue;
      }
      if (VOID_DISALLOWED.has(tag)) {
        // Skip past the opening tag AND the body, up to the closing
        // tag of the same name (or end of string). We do this with a
        // non-greedy match so nested/wrongly-cased forms also get
        // dropped correctly.
        const bodySkip = src.slice(lt).match(
          new RegExp(`^<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}\\s*>`, 'i')
        );
        if (bodySkip) {
          i = lt + bodySkip[0].length;
        } else {
          // No closing tag found: drop the opening tag itself, and
          // let the rest of the parser run on whatever comes next.
          i = lt + openMatch[0].length;
        }
        continue;
      }
      // Unknown / non-void tag: drop the tag, keep the text content
      // (the loop will emit the next run of text on the next iteration).
      i = lt + openMatch[0].length;
      continue;
    }
    // Doctype / processing instructions / CDATA: drop the bracket and
    // emit it as text. The rest of the stream is re-evaluated.
    out += '&lt;';
    i = lt + 1;
  }
  return out;
}

// ---------------------------------------------------------------------------
// HTML → text (very small, signature-only).
// ---------------------------------------------------------------------------

/**
 * Convert a (sanitized) HTML signature to a plain-text version.
 * - <br> → \n
 * - Block tags (p, div, h*, li, tr) → \n before + \n after
 * - All other tags are stripped, keeping inner text.
 * - Entities are decoded.
 */
export function htmlToText(html) {
  if (!html || typeof html !== 'string') return '';
  let s = html;
  // Block-level: add a newline before opening and after closing.
  const blockOpen = /<(p|div|h[1-6]|li|tr|blockquote)\b[^>]*>/gi;
  s = s.replace(blockOpen, '\n');
  // <br> → single newline
  s = s.replace(/<br\b[^>]*\/?>/gi, '\n');
  // Closing block tags also get a trailing newline.
  s = s.replace(/<\/(p|div|h[1-6]|li|tr|blockquote)\s*>/gi, '\n');
  // <hr> → dash line
  s = s.replace(/<hr\b[^>]*\/?>/gi, '\n---\n');
  // Strip remaining tags.
  s = s.replace(/<[^>]+>/g, '');
  // Decode the named entities we generated + the common 5.
  s = s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&');
  // Collapse runs of >2 blank lines down to 2.
  s = s.replace(/\n{3,}/g, '\n\n');
  return s.trim();
}

// ---------------------------------------------------------------------------
// settings + signature lookup
// ---------------------------------------------------------------------------

function getSetting(db, key) {
  if (!db) return null;
  const row = db.prepare('SELECT value FROM settings WHERE key = ?').get(key);
  return row ? row.value : null;
}

/**
 * Read the configured signature. Returns null if no signature is set.
 * Honors the `email_signature_format` setting:
 *   - 'html' → returns the rich (sanitized) signature, plus a derived
 *     plain-text form.
 *   - anything else (or unset) → returns the plain-text signature.
 */
export function getEmailSignature(db) {
  if (!db) return null;
  const format = String(getSetting(db, 'email_signature_format') || 'plain').toLowerCase();
  if (format === 'html') {
    const raw = String(getSetting(db, 'email_signature_html') || '').trim();
    if (!raw) return null;
    const safeHtml = sanitizeRichSignature(raw);
    const text = htmlToText(safeHtml);
    if (!text) return null;
    return {
      raw,                          // canonical config value (for dedupe)
      text,                         // derived plain-text
      html: `<div style="margin-top:1em;padding-top:0.75em;border-top:1px solid #e5e7eb;color:#475569;font-size:0.9em">${safeHtml}</div>`,
      format: 'html',
    };
  }
  const raw = String(getSetting(db, 'email_signature') || '').trim();
  if (!raw) return null;
  return {
    raw,
    text: raw,
    html: `<div style="margin-top:1em;padding-top:0.75em;border-top:1px solid #e5e7eb;color:#475569;font-size:0.9em;white-space:pre-wrap">${escapeHtml(raw)}</div>`,
    format: 'plain',
  };
}

/**
 * Append the signature to a body. Returns `{ text, html }` suitable
 * for `sendEmail`. If the signature is null, returns the original
 * body unchanged.
 *
 * Idempotent: if the (trimmed) body already ends with the exact
 * signature text (plain mode) OR the exact raw HTML (html mode), the
 * signature is not appended again. This protects against
 * double-appends caused by frontend/backend retries or admins who
 * copy-paste the signature block into a draft twice.
 */
export function appendSignature(db, body) {
  const sig = getEmailSignature(db);
  if (!sig) return { text: body, html: null };
  const trimmed = (body || '').replace(/\s+$/, '');
  if (sig.format === 'html') {
    // Dedupe HTML: if the (trimmed) body already ends with the raw
    // HTML signature (admin copy-pasted the preview) OR with the
    // wrapped HTML form we generate, OR with the "--\n<raw>" form
    // (admin copy-pasted the rendered preview that includes the
    // separator), skip. The last case is the most common in
    // practice — admins paste the "Hi Linda\n\n--\n<sig>" form they
    // see in the plain-text preview.
    if (trimmed === sig.raw) return { text: trimmed, html: null };
    if (trimmed.endsWith(sig.html)) return { text: trimmed, html: null };
    if (trimmed.endsWith(`--\n${sig.raw}`)) return { text: trimmed, html: null };
    return {
      text: `${trimmed}\n\n--\n${sig.text}`,
      html: `<div style="white-space:pre-wrap">${escapeHtml(trimmed)}</div>\n${sig.html}`,
    };
  }
  // Plain mode (unchanged from the original implementation).
  if (trimmed === sig.raw) return { text: trimmed, html: null };
  if (trimmed.endsWith(`--\n${sig.raw}`)) return { text: trimmed, html: null };
  return {
    text: `${trimmed}\n\n--\n${sig.text}`,
    html: `<div style="white-space:pre-wrap">${escapeHtml(trimmed)}</div>\n${sig.html}`,
  };
}
